### ISSUE TITLE
run_collection error

### ISSUE THREAD

**Issue by skytguuu** [lisc-tools/lisc#74]
Hi,

I met a problem about the 'words.run_collection'. When I did the tutorial as followed:
#######################
db = SCDB('lisc_db')
words.run_collection(usehistory=True, retmax=15, save_and_clear=True, directory=db)
#######################
It reorted an error that:
FileNotFoundError: {Errno 2] No such file or directory: 'lisc_db\\data\\words\\raw\\ovary.jason'

Could you give me a hand?
Thanks!

**Comment by TomDonoghue** [comment]
Hey @skytguuu - not sure if you meant to close this and/or hopefully already figured this out - but it looks like the issue is that the folder you are trying to save to has not been created. 

In the tutorials, the examples are expected to be run in order, so the [first tutorial ](https://lisc-tools.github.io/lisc/auto_tutorials/plot_00-Overview.html#sphx-glr-auto-tutorials-plot-00-overview-py) has a section on defining the database (that gets used in subsequent examples), and also [this example](https://lisc-tools.github.io/lisc/auto_examples/plot_db_terms.html#sphx-glr-auto-examples-plot-db-terms-py) further describes the database structure.

**Comment by skytguuu** [comment]
Thanks for your reply. The question was solved. 
Thanks!
